Working VDM Demo apps in gerrit.
 - Switch from nearby to Wifi Aware
 - Add Android.bp
 - Update README
 - Fix the permission revoke button

Looks like POST_NOTIFICATIONS cannot be self-revoked:
IllegalArgumentException: Cannot revoke permission POST_NOTIFICATIONS
for package [...] since POST_NOTIFICATIONS does not belong to a
permission group

NO_IFTTT=updating existing docs

Fix: 315113801
Test: build and install and run
Change-Id: I96f06a7e6b27242d8ae19c0eed2dfe88060f8b12